# kitti_full.yaml

path: C:\Users\amanu\Desktop\Projects\real_time_object_detection/final_dataset

train: train/images
val: val/images

names:
  0: Car
  1: Truck
  2: Pedestrian
  3: Cyclist
  4: Van
  5: Person_sitting
  6: Tram
  7: Misc
